[[nouns]]
title = "adjutor"
synopsis = "adjūtor"
genitive = "adjūtōris"
plural_genitive = "adjūtōrum"
declension = 3
gender = "masculine"
translation = "救い手"

[[nouns]]
title = "anima"
synopsis = "anima"
genitive = "animae"
declension = 1
gender = "feminine"
translation = "魂"
[[nouns.examples]]
latin = "**Tris**tis est **a**nima **me**a."
japanese = "私の魂は悲しい。"
[[nouns.examples]]
latin = "Jus**tō**rum **a**nimae in **ma**nū **De**ī sunt."
japanese = "正しい者たちの魂たちは神の手の中にある。"

[[nouns]]
title = "animal"
synopsis = "animal"
genitive = "animalis"
plural_genitive = "animalium"
declension = 3
gender = "neuter"
translation = "動物"

[[nouns]]
title = "canticum"
synopsis = "canticum"
genitive = "canticī"
declension = 2
gender = "neuter"
translation = "歌"

[[nouns]]
title = "dolor"
synopsis = "dolor"
genitive = "dolōris"
plural_genitive = "dolōrum"
declension = 3
gender = "masculine"
translation = "悲しみ"
[[nouns.examples]]
latin = "Vi**dē**te do**lō**rem **me**um. (『哀歌』第 1 章第 18 節)"
japanese = "(あなたたちは) 私の苦しみを見ろ。"
[[nouns.examples]]
latin = "quī do**lō**rem **ip**sum **qui**a **do**lor sit **a**met"
japanese = "悲しみ自身を、それが悲しみであるゆえに愛する者"

[[nouns]]
title = "mare"
synopsis = "mare"
genitive = "maris"
plural_genitive = "marium"
declension = 3
gender = "neuter"
translation = "海"
[[nouns.examples]]
latin = "Avē, maris stella."
japanese = "こんにちは、海の星よ。"

[[nouns]]
title = "mors"
synopsis = "mors"
genitive = "mortis"
plural_genitive = "mortium"
declension = 3
gender = "feminine"
translation = "死"
[[nouns.examples]]
latin = "Dā **mi**hi **mor**tem **i**terum."
japanese = "(あなたは) 再び私に死を与えろ。"
[[nouns.examples]]
latin = "**Es**tō **nō**bīs praegus**tā**tum **mor**tis in ex**ā**mine."
japanese = "(あなたは) 死の試練において、私たちのためにあらかじめ試練を試す者となれ。"
[[nouns.examples]]
latin = "**I**bi **nul**lus **ti**met **mor**tem."
japanese = "ここでは誰も死を恐れない。"

[[nouns]]
title = "propheta"
synopsis = "prophēta"
genitive = "prophētae"
declension = 1
gender = "masculine"
translation = "預言者"
[[nouns.examples]]
latin = "Quī lo**cū**tus est per Pro**phē**tās."
japanese = "それは預言者たちを通して語った。"
