[[nouns]]
title = "oculus"
synopsis = "oculus"
genitive = "oculī"
declension = 2
gender = "masculine"
translation = "目"
[[nouns.examples]]
latin = "**Qui**a vi**dē**runt **o**culī **me**ī salū**tā**re **tu**um."
japanese = "なぜなら、私の目たちはあなたの救済を見たからだ。"

[[nouns]]
title = "robur"
synopsis = "rōbur"
genitive = "rōburis"
plural_genitive = "rōburum"
declension = 3
gender = "neuter"
translation = "力"

[[nouns]]
title = "auxilium"
synopsis = "auxilium"
genitive = "auxiliī"
declension = 2
gender = "neuter"
translation = "助け"

[[nouns]]
title = "dominus"
synopsis = "dominus"
genitive = "dominī"
declension = 2
gender = "masculine"
translation = "主"
