[[nouns]]
title = "via"
synopsis = "via"
genitive = "viae"
declension = 1
gender = "feminine"
translation = "道"
[[nouns.examples]]
latin = "Tran**sī**tis per **vi**am."
japanese = "あなたたちは道を通って行く。"

[[nouns]]
title = "gloria"
synopsis = "glōria"
genitive = "glōriae"
declension = 1
gender = "feminine"
translation = "栄光"

[[nouns]]
title = "dextera"
synopsis = "dextera"
genitive = "dexterae"
declension = 1
gender = "feminine"
translation = "右側"
[[nouns.examples]]
latin = "**Il**lī mens est **mi**sera quī nec **vī**vit nec las**cī**vit sub es**tā**tis **dex**terā."
japanese = "夏の右手 (制御権) の下にありながら、活発になろうともせず、跳ね回ろうともしない、そんな奴の心は惨めだ。"

[[nouns]]
title = "vita"
synopsis = "vīta"
genitive = "vītae"
declension = 1
gender = "feminine"
translation = "命"

[[nouns]]
title = "peccatum"
synopsis = "peccātum"
genitive = "peccātī"
declension = 2
gender = "neuter"
translation = "罪"

[[nouns]]
title = "Dominus"
synopsis = "Dominus"
genitive = "Dominī"
declension = 2
gender = "masculine"
translation = "主"

[[nouns]]
title = "spiritus"
synopsis = "spīritus"
genitive = "spīritūs"
declension = 4
gender = "masculine"
translation = "魂"

[[nouns]]
title = "pax"
synopsis = "pax"
genitive = "pācis"
plural_genitive = "pācum"
declension = 3
gender = "feminine"
translation = "平和"
[[nouns.examples]]
latin = "In **ter**rā pax ho**mi**nibus **bo**nae volun**tā**tis."
japanese = "地において、平和が善意の人間たちにありますように。"
[[nouns.examples]]
latin = "**Il**lī sunt in **pā**ce."
japanese = "彼らは平和のうちにいる。"

[[nouns]]
title = "deprecatio"
synopsis = "dēprecātiō"
genitive = "dēprecātiōnis"
plural_genitive = "dēprecātiōnum"
declension = 3
gender = "feminine"
translation = "祈り"

[[nouns]]
title = "pater"
synopsis = "pater"
genitive = "pātris"
plural_genitive = "patrum"
declension = 3
gender = "masculine"
translation = "父"

[[nouns]]
title = "factor"
synopsis = "factor"
genitive = "factōris"
plural_genitive = "factorum"
declension = 3
gender = "masculine"
translation = "作り手"

[[nouns]]
title = "requies"
synopsis = "requiēs"
genitive = "requiem"
declension = 5
gender = "feminine"
translation = "安息"

[[nouns]]
title = "resurrectio"
synopsis = "resurrectiō"
genitive = "resurrectiōnis"
plural_genitive = "resurrectiōnum"
declension = 3
gender = "feminine"
translation = "復活"

[[nouns]]
title = "robur"
synopsis = "rōbur"
genitive = "rōburis"
plural_genitive = "rōburum"
declension = 3
gender = "neuter"
translation = "力"

[[nouns]]
title = "gratia"
synopsis = "grātia"
genitive = "grātiae"
declension = 1
gender = "feminine"
translation = "感謝"

[[nouns]]
title = "vivus"
synopsis = "vīvus"
genitive = "vīvī"
declension = 2
gender = "masculine"
translation = "生者"

[[nouns]]
title = "mortuus"
synopsis = "mortuus"
genitive = "mortuī"
declension = 2
gender = "masculine"
translation = "死者"

[[nouns]]
title = "manus"
synopsis = "manus"
genitive = "manūs"
declension = 4
gender = "feminine"
translation = "手"
[[nouns.examples]]
latin = "**Pa**ter, in **ma**nūs **tu**ās com**men**dō **spī**ritum **me**um."
japanese = "父よ、私はあなたの両手へと私の魂を委ねる。"

[[nouns]]
title = "malum"
synopsis = "malum"
genitive = "malī"
declension = 2
gender = "neuter"
translation = "悪"
[[nouns.examples]]
latin = "Mala nostra pelle."
japanese = "私たちの悪を追い払え。"

[[nouns]]
title = "bonum"
synopsis = "bonum"
genitive = "bonī"
declension = 2
gender = "neuter"
translation = "善"
[[nouns.examples]]
latin = "Bona cuncta posce."
japanese = "すべての善を願え。"
