[[nouns]]
title = "sors"
synopsis = "sors"
genitive = "sortis"
plural_genitive = "sortium"
declension = 3
gender = "feminine"
translation = "運命"
[[nouns.examples]]
latin = "Sed prō **Bac**chō **mit**tunt **sor**tem."
japanese = "そうではなく、バックスのために彼らは運命を投じるのだ。"

[[nouns]]
title = "ira"
synopsis = "īra"
genitive = "īrae"
declension = 1
gender = "feminine"
translation = "怒り"
[[nouns.examples]]
latin = "**Di**ēs **ī**rae, **di**ēs **il**la **sol**vet **saec**lum in fa**vil**lā."
japanese = "怒りの日、その日は世界を灰の中で粉々にするだろう。"

[[nouns]]
title = "mors"
synopsis = "mors"
genitive = "mortis"
plural_genitive = "mortium"
declension = 3
gender = "feminine"
translation = "死"
